### ISSUE TITLE
Auto-test 'Web Security' mrHoft

### ISSUE THREAD

**Issue by mrHoft** [rolling-scopes-school/support#962]
I am passed the Web Security test and receive 0 score for it. It can not be possible cause my first attempt was 85.
Opened [issue](https://github.com/rolling-scopes-school/support/issues/961), that was fixed and closed.
But I still have 0 points for this test. Attempt to know which of the answers were determined to be incorrect, results in an error:
```
TypeError: Z.value.includes is not a function
    at h (3453-669a06f2ab3def8e.js:1:2079)
Error rendering page:  Error: Cancel rendering route
    at c (main-706ae940f5b39ca6.js:1:10808)
```
Please, return my confirmed score back.

![image](https://github.com/rolling-scopes-school/support/assets/51874769/c6a7e044-d5fd-4c54-9bb4-2b5059574c90)

**Comment by mrHoft** [comment]
@valerydluski helped me with this problem.
